// All 11 data-panel content blocks — copy is verbatim from the creative brief.
export const PANELS = {
  hero: {
    index: 0,
    type: "hero",
    eyebrow: "Intelligent Business Systems",
    title: "Every Business Runs On Systems.",
    body: "The businesses that thrive tomorrow will have smarter systems than their competitors. Customer systems. Operations systems. Knowledge systems. Growth systems.",
    ctas: [
      { label: "Get AI & Automation Assessment", variant: "primary" },
      { label: "Book Strategy Session", variant: "secondary" },
    ],
  },
  neuralCore: {
    index: 1,
    type: "intro",
    eyebrow: "The Living IT Ecosystem",
    title: "Your Business Is One Connected System.",
    body: "Customer, operations, knowledge and growth systems aren't separate tools — they're a single living organism. We design the intelligence that connects them so your business thinks, adapts, and scales as one.",
  },
  scaleChanged: {
    index: 1,
    type: "stats",
    eyebrow: "The Shift",
    title: "The Way Businesses Scale Has Changed.",
    body: "For decades, growth followed a predictable formula: More Customers \u2192 More Employees \u2192 More Overhead. Today's leading businesses are building smarter systems instead \u2014 combining people, AI, automation, and software to achieve more with less complexity.",
    stats: ["Rising Labor Costs", "Growing Customer Expectations", "Increasing Competition"],
    insight: "Adding more people is no longer the most effective path to growth.",
  },
  systemsProblem: {
    index: 2,
    type: "pills",
    eyebrow: "The Core Problem",
    title: "Most Businesses Don't Have A Technology Problem. They Have A Systems Problem.",
    body: "Many businesses already have the tools they need. The challenge is that those tools rarely work together. Information lives in different places. Processes rely on manual effort.",
    pills: ["Missed Opportunities", "Slower Operations", "Inconsistent Experiences", "Increasing Costs"],
    insight: "Technology alone doesn't solve this. Better systems do.",
  },
  fiveSystems: {
    index: 3,
    type: "pillars",
    eyebrow: "The Five Systems",
    title: "Every Business Depends On Five Critical Systems.",
    cards: [
      { title: "Customer Growth Systems", body: "How you attract, engage, nurture, and convert customers. Without a reliable growth system, opportunities are lost and revenue becomes unpredictable.", color: "#059669" },
      { title: "Customer Experience Systems", body: "How customers interact with your business before, during, and after every purchase. Great experiences create loyalty. Poor experiences create churn.", color: "#0E9E86" },
      { title: "Business Operations Systems", body: "How work gets done across your organisation. Efficient systems reduce delays, improve consistency, and increase profitability.", color: "#E08A0B" },
      { title: "Workforce Productivity Systems", body: "How employees access information, complete tasks, and collaborate. The right systems help teams achieve more without increasing workload.", color: "#7C3AED" },
      { title: "Operational Intelligence Systems", body: "How leaders monitor performance and make decisions. Better visibility leads to better outcomes.", color: "#2563EB" },
    ],
  },
  challenges: {
    index: 4,
    type: "challenges",
    eyebrow: "The Challenges We Solve",
    title: "The Six Challenges We Help You Overcome.",
    rows: [
      { title: "Generate More Leads", body: "Create intelligent customer acquisition systems that attract, qualify, and convert." },
      { title: "Improve Customer Experience", body: "Deliver faster responses, personalised engagement, consistent support." },
      { title: "Reduce Manual Work", body: "Automate repetitive tasks and eliminate operational bottlenecks." },
      { title: "Improve Team Productivity", body: "Empower employees with knowledge, automation, and AI assistance." },
      { title: "Gain Operational Visibility", body: "Transform fragmented information into actionable insights." },
      { title: "Scale Without Growing Complexity", body: "Build systems that support sustainable growth without increasing overhead." },
    ],
  },
  framework: {
    index: 5,
    type: "framework",
    eyebrow: "Our Framework",
    title: "Build. Automate. Scale.",
    columns: [
      { title: "Build", subtitle: "Create the digital foundation for growth.", bullets: ["High-Performance Websites", "Customer Portals", "SaaS Platforms", "Mobile Applications", "Business Applications"] },
      { title: "Automate", subtitle: "Reduce manual work and increase efficiency.", bullets: ["AI Agents", "Voice AI Assistants", "Workflow Automation", "Knowledge Assistants", "Digital Employees"] },
      { title: "Scale", subtitle: "Turn technology into competitive advantage.", bullets: ["Improve Customer Acquisition", "Increase Productivity", "Standardise Operations", "Gain Operational Intelligence", "Accelerate Growth"] },
    ],
  },
  digitalWorkers: {
    index: 6,
    type: "workers",
    eyebrow: "Digital Workers & Voice AI",
    title: "Expand Your Workforce Without Expanding Your Headcount.",
    body: "Deploy intelligent digital workers that answer questions, support customers, assist employees, and execute business processes 24/7.",
    workers: [
      { title: "Sales Development Worker", body: "Engage prospects instantly. Qualify opportunities. Never miss a lead." },
      { title: "Front Desk Worker", body: "Every call answered. Every enquiry captured. Every opportunity managed." },
      { title: "Customer Service Worker", body: "Exceptional customer service, available 24/7, at scale." },
      { title: "Knowledge Worker", body: "Put your organisational knowledge to work. Instant answers for every employee." },
      { title: "Operations Worker", body: "Keep your business moving even when your team is busy." },
      { title: "Executive Intelligence Worker", body: "Better decisions start with better visibility." },
    ],
    cta: { label: "Book Digital Worker Consultation", variant: "primary" },
  },
  intellSystems: {
    index: 7,
    type: "systems",
    eyebrow: "Intelligent Systems",
    title: "Technology Should Simplify Business. Not Complicate It.",
    body: "We help organisations design systems that connect people, processes, information, and AI into one cohesive operating environment.",
    cards: [
      { title: "Growth Systems", body: "Acquire and convert customers more effectively." },
      { title: "Experience Systems", body: "Deliver exceptional customer interactions." },
      { title: "Operations Systems", body: "Improve efficiency and reduce operational friction." },
      { title: "Productivity Systems", body: "Empower employees with intelligent tools and automation." },
      { title: "Intelligence Systems", body: "Gain visibility across the business and make informed decisions." },
    ],
  },
  industries: {
    index: 8,
    type: "industries",
    eyebrow: "Industries We Support",
    title: "Every Industry Faces Unique Operational Challenges.",
    body: "Our solutions are tailored to the realities of each sector.",
    tabs: [
      { key: "healthcare", label: "Healthcare", body: "Improve patient experiences, reduce administrative burden, and empower healthcare teams." },
      { key: "automotive", label: "Automotive", body: "Capture more opportunities, improve customer engagement, and streamline service operations." },
      { key: "construction", label: "Construction", body: "Improve project visibility, workforce coordination, and operational performance." },
      { key: "professional", label: "Professional Services", body: "More clients. Better service. Higher productivity. Intelligent systems for modern firms." },
      { key: "manufacturing", label: "Manufacturing", body: "Smarter operations. Better visibility. Greater efficiency across production environments." },
    ],
  },
  whyHow: {
    index: 9,
    type: "whyHow",
    eyebrow: "Why Businesses Choose IPangram",
    title: "Outcome-Focused. Practical. End-To-End.",
    reasons: [
      { title: "Outcome-Focused", body: "We focus on business outcomes, not technology trends." },
      { title: "Practical AI", body: "Real-world solutions designed to create measurable impact." },
      { title: "End-To-End", body: "From strategy and architecture to implementation and optimisation." },
      { title: "Future-Ready", body: "Built for organisations preparing for the next decade of business." },
    ],
    processEyebrow: "How We Work",
    processTitle: "A Five-Step Process. No Surprises.",
    steps: [
      { title: "Discover", body: "Understand your business, systems, and goals." },
      { title: "Assess", body: "Identify opportunities for AI, automation, and optimisation." },
      { title: "Design", body: "Create a practical roadmap aligned with business outcomes." },
      { title: "Build", body: "Develop and deploy intelligent business systems." },
      { title: "Optimise", body: "Continuously improve performance, adoption, and results." },
    ],
  },
  finalCTA: {
    index: 10,
    type: "finalCTA",
    eyebrow: "The Future Belongs To Smarter Businesses",
    title: "Ready To Build A Smarter Business?",
    body: "Your competitors are already exploring how AI, automation, and intelligent systems can transform the way they operate. The question is whether you'll lead the change or react to it.",
    ctas: [
      { label: "Get AI & Automation Assessment", variant: "primary" },
      { label: "Book Strategy Session", variant: "secondary" },
    ],
    socialProof: "Trusted by growing businesses across Healthcare, Automotive, Professional Services, Construction, and Manufacturing.",
  },
};

export const PANEL_ORDER = [
  "hero",
  "neuralCore",
  "scaleChanged",
  "systemsProblem",
  "fiveSystems",
  "challenges",
  "framework",
  "digitalWorkers",
  "intellSystems",
  "industries",
  "whyHow",
  "finalCTA",
];
